version: '3.8'

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db
        environment:
            - DEBUG=TRUE
            - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase

    db:
        image: postgres
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"
